on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://gitlab.com/AlfonsoML/pogo-s2.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
